### ISSUE TITLE
Error creating plan with 0 amount

### ISSUE THREAD

**Issue by korovaisdead** [stripe/stripe-go#513] opened 2018-01-29 14:10 UTC
The code below causes the error from the REST endpoint:

`Error encountered from Stripe: {"status":400,"message":"Plans require an `amount` parameter to be set.","param":"amount","request_id":"-some-req-id-","type":"invalid_request_error"}`

looks like it omits the empty value of the `Amount` during form serialization...

```
func (s *StripeClientImpl) CreatePlan(planid string) (*stripe.Plan, error) {
    param := &stripe.PlanParams{
         ID:       planid,
         Amount:   0,
         Interval: "month",
         Name:     planid,
         Currency: "usd",
      }
     s.log.Info(param.Amount)
     p, err := plan.New(param)

     if err != nil {
         return nil, err
     }

     return p, nil
 }
```

**Comment by remi-stripe** [comment] 2018-01-29 14:46
@korovaisdead The issue is that when the amount is zero, the library is not sending the value properly to the server which makes us reject the request. I'll work on a fix that will be merged in the next few days.

In the meantime, you likely want to create the plan manually in the dashboard.

**Closed** 2018-01-29 19:41 UTC
