### ISSUE TITLE
x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by parazyd** [stripe/stripe-go#1003] opened 2019-12-12 19:01 UTC
I have deployed a checkout page with a go daemon and with nginx serving https and doing a proxy_pass to the go daemon. The TLS certificate is valid, and issued by Letsencrypt. However, when I try to actually perform the checkout, I get the following error:

```
Post https://api.stripe.com/v1/checkout/sessions: x509: certificate signed by unknown authority
```

Can anyone help me with debugging this problem?

Go version: 1.13.4
stripe-go version: Latest git

**Comment by richardm-stripe** [comment] 2019-12-16 19:43
Hi @parazyd.

That error message means the [golang tls library](https://golang.org/pkg/crypto/tls/) cannot find the root ca certificate it needs to verify the responses from the Stripe API.

I recommend trying this command on the same system as your go daemon is running to make an https request to Stripe, outside of the go process

```sh
curl -Iv https://stripe.api.com
```
from the same system as your go daemon is running. If this *doesn't* give you an SSL error, that's a sign that the issue is specific to your go process -- you should check to see that the `SSL_CERT_FILE` and `SSL_CERT_DIR` [environment variables](https://golang.org/src/crypto/x509/root_unix.go) aren't being set to the wrong location.

Otherwise, the problem is likely with your system-wide configuration of certificate authorities. At a high level, [this CA root](https://ev-root.chain-demos.digicert.com/info/index.html) needs to be trusted by your system.

How certificate authorities are configured varies a lot from system to system, but for example, on an Alpine docker container with the `ca-certificates` package installed, they generated from `/etc/ca-certificates.conf` which references the cert at `/usr/share/ca-certificates/mozilla/DigiCert_High_Assurance_EV_Root_CA.crt`. (Without `ca-certificates` the cert is simply contained in `/etc/ssl/cert.pem`). On your system, the locations might be different.

Hope this points you in the right direction.

**Comment by richardm-stripe** [comment] 2020-02-21 18:49
@parazyd closing for now, please let us know if you discover this issue is related to stripe-go!

**Closed by richardm-stripe** 2020-02-21 18:49 UTC
