### ISSUE TITLE
webhook.ConstructEvent failed to parse webhook body

### ISSUE THREAD

**Issue by ddelizia** [stripe/stripe-go#1333] opened 2021-09-01 11:00 UTC
Hi, 
I am using this library in my code to process events coming from stripe. I am following the instruction of this page https://dashboard.stripe.com/test/webhooks/create?endpoint_location=local and using the stripe CLI to generate events.

At this line:
```
event, err := webhook.ConstructEvent(b, r.Header.Get("Stripe-Signature"), "whsec_<secret_outputted_by_cli_tool>")
```

I get the following error:

```
Failed to parse webhook body json: json: cannot unmarshal string into Go struct field Event.request of type stripe.EventRequest
```

Based on some thread I found, it seems to be related with the version of the event, and this is the version of the even generated by the CLI

```
{
  "id": "evt_3JUpn7FqtLrMpqCW0JlyW4Cm",
  "object": "event",
  "api_version": "2015-04-07",
  "created": 1630488697,
  "data": {
    "object": {
      "id": "ch_3JUpn7FqtLrMpqCW06aYRpwH",
  ....
}
```

Go version: `go version go1.16.6 linux/amd64`
Stripe-Go Version: `github.com/stripe/stripe-go/v72@v72.45.0`

**Comment by ddelizia** [comment] 2021-09-01 12:19
Looking at the code it seems thet is expecting the `request` property to be an object instead of a string:

```
// Event is the resource representing a Stripe event.
// For more details see https://stripe.com/docs/api#events.
type Event struct {
	Account         string        `json:"account"`
	Created         int64         `json:"created"`
	Data            *EventData    `json:"data"`
	ID              string        `json:"id"`
	Livemode        bool          `json:"livemode"`
	PendingWebhooks int64         `json:"pending_webhooks"`
	Request         *EventRequest `json:"request"`
	Type            string        `json:"type"`
}

// EventRequest contains information on a request that created an event.
type EventRequest struct {
	// ID is the request ID of the request that created an event, if the event
	// was created by a request.
	ID string `json:"id"`

	// IdempotencyKey is the idempotency key of the request that created an
	// event, if the event was created by a request and if an idempotency key
	// was specified for that request.
	IdempotencyKey string `json:"idempotency_key"`
}
```

Is there any way with the CLI tool to create such messages?

**Comment by remi-stripe** [comment] 2021-09-02 06:25
@ddelizia The problem is that the stripe-go library is pinned to a specific API version where the shape of each object is defined/static. Your code is trying to handle an event on a real old API version (2015-04-07) with a recent stripe-go. At the time, over 6 years ago the `request` property was a `string` instead of a hash and this changed a few years later in [2017-05-25](https://stripe.com/docs/upgrades#2017-05-25)

The version of the CLI itself does not matter in this flow. Events are generated based on the default API version of your Stripe account which is likely really old at the moment. What you can do instead is create a webhook endpoint pinned to a specific API version with the [api_version](https://stripe.com/docs/api/webhook_endpoints/create#create_webhook_endpoint-api_version) parameter to force events to be generated with the correct API version matching the library's version, currently `2020-08-27`

Similarly, with the CLI you can use the `--latest` flag documented [here](https://stripe.com/docs/cli/listen#listen-latest) to force events in the latest API version.

I hope this helps but I'm going to close this issue as it's not really a bug with the library itself and more an integration question. If you have a follow up question, please ask our support team for help on https://support.stripe.com/contact or on our Discord community server https://stripe.com/go/developer-chat

**Closed by remi-stripe** 2021-09-02 06:25 UTC
