### ISSUE TITLE
error creating a subscription "No such customer" but the customer is there

### ISSUE THREAD

**Issue by alfmos** [stripe/stripe-go#1338] opened 2021-09-05 17:41 UTC
I created a customer, and then I created a subscription to a connected account.
result is 404 saying the customer doesn't exists. But he does. the code is:
```
	// Create subscription
	subscriptionParams := &stripe.SubscriptionParams{
		Customer: stripe.String(memberUser.Stripe_Member_Account_ID.String),
		Items: []*stripe.SubscriptionItemsParams{
			{
				Price: stripe.String(userMembershipType.Stripe_Price_ID.String),
			},
		},
		ApplicationFeePercent: stripe.Float64(10),
		//		TransferData:    &transferData,
		PaymentBehavior: stripe.String("default_incomplete"),
	}
	//set the creator account as the one who will receive the entire amount minus ApplicationFeePErcent
	subscriptionParams.SetStripeAccount(membershipUser.Stripe_Membership_Account_ID.String)

	// ask stripe to return latest invoice from where we'll take paymentIntent
	subscriptionParams.AddExpand("latest_invoice.payment_intent")

	Log.Logga("Creating a subscription with these parameters (stripeAccount): ", *subscriptionParams.StripeAccount, multilog.LOGBASE)
	Log.Logga("Creating a subscription with these parameters (customer): ", *subscriptionParams.Customer, multilog.LOGBASE)

	var s *stripe.Subscription
	s, rerr.Err = sub.New(subscriptionParams)
	if rerr.IsNotNil() {
		Log.Error("Error creating Stripe subscription: ", false, rerr.Error())
		response.StatusCode = http.StatusBadRequest
		response.Body = rerr.JSONString()
		return &response, rerr
	}
```
**Logs are:**
INFO |subscribestripeuserandpayCtrl.go:103 controller.SubscribeUserCTRL.SubscribeStripeUserAndPayInternal|Creating a subscription with these parameters (customer): | cus_KAkJvmC7c9237U

INFO |subscribestripeuserandpayCtrl.go:103 controller.SubscribeUserCTRL.SubscribeStripeUserAndPayInternal|Creating a subscription with these parameters (stripeAccount): | acct_1JRj8A2HebUq4Fqg

**And I receive this error from Stripe:**
[ERROR] Request error from Stripe (status 404): {
    "code": "resource_missing",
    "doc_url": "https://stripe.com/docs/error-codes/resource-missing",
    "status": 404,
    "message": "No such customer: 'cus_KAkJvmC7c9237U'",
    "param": "customer",
    "request_id": "req_Rn9m90CGzA1MTH",
    "type": "invalid_request_error"
}

Of course customer and connected users both exists

**Comment by remi-stripe** [comment] 2021-09-06 04:17
@alfmos Github issues should be limited to bugs with the stripe-go library. This is an integration/support question about a bug in your code so you should talk to our support team directly https://support.stripe.com/contact or talk to other developers on our Discord community server: https://stripe.com/go/developer-chat

To unblock you though the problem is that the Customer is created on the platform account (your account) but the Subscription is created on the connected account since you use Direct Charges. This can not work, the Customer has to exist on the same account as the Subscription. So you need to make sure you do that. If you want to have the Customer on the platform it's doable but you can not use that one. The idea is to create a "separate" Customer on the connected account and then you can also clone PaymentMethods as documented [here](https://stripe.com/docs/payments/payment-methods/connect).

I'm going to close this out but hopefully this gives you a good starting point.

**Closed by remi-stripe** 2021-09-06 04:17 UTC

**Comment by alfmos** [comment] 2021-09-06 07:15
Hi Remi,
I made a last minute change and I didn't realize it made me switching to Direct Charges, and it seemed a bug to me.
Sorry to waste your time, and thanks for pointing me in the right direction.
By the way, checking the link you sent, there is this example:
```
// Set your secret key. Remember to switch to your live secret key in production.
// See your keys here: https://dashboard.stripe.com/apikeys
stripe.Key = 

"sk_test_******************************************************"


params := &stripe.SubscriptionParams{
  Customer: stripe.String("cus_**********"),
  Items: []*stripe.SubscriptionItemsParams{
    {
      price: stripe.String("price_*"),
    },
  },
  ApplicationFeePercent: stripe.Float64(10),
  TransferData: &stripe.InvoiceTransferDataParams{
    Destination: stripe.String("{{CONNECTED_STRIPE_ACCOUNT_ID}}"),
  },
}
params.AddExpand("latest_invoice.payment_intent")

subscription, _ := sub.New(params)
```
It seems to me that this row is wrong:
```
 TransferData: &stripe.InvoiceTransferDataParams{
    Destination: stripe.String("{{CONNECTED_STRIPE_ACCOUNT_ID}}"),
  },
```
 and should be:
```
TransferData: &stripe.SubscriptionTransferDataParams{
  Destination: stripe.String(membershipUser.Stripe_Membership_Account_ID.String),
},		
```
but maybe I am wrong again :)

**Comment by remi-stripe** [comment] 2021-09-08 03:16
@alfmos Thanks for the report. I'm working on fixing those and hopefully can merge the changes tomorrow!

**Comment by remi-stripe** [comment] 2021-09-08 23:28
@alfmos Code examples were fixed! Thanks again for the report!

**Comment by alfmos** [comment] 2021-09-09 04:45
@remi-stripe  you're welcome. Thanks to you for pointing me to the solutione even if it wasn't a bug
