### ISSUE TITLE
Metadata for new Scheduled Subscription are not saved

### ISSUE THREAD

**Issue by testfully-dev** [stripe/stripe-go#1265] opened 2021-03-16 11:05 UTC
I'm trying to get my head around metadata and scheduled subscriptions. By looking at the reference API docs, it looks like that I should be able to set some metadata while adding a new scheduled subscription but stripe-go doesn't save the metadata. I have tried both `.Params.Metadata` and `.AddMetadata`. My code looks like this:

```golang
subscriptionParams := stripe.SubscriptionScheduleParams{
	Customer:    stripe.String(workspace.StripeCustomerID),
	EndBehavior: stripe.String(string(stripe.SubscriptionScheduleEndBehaviorRelease)),
	Phases:      []*stripe.SubscriptionSchedulePhaseParams{},
}
```

and then I have some metadata:

```golang
metadata := map[string]string{
	"requested_at": time.Now().Format(time.RFC1123),
         "workspace_id": " workspace.ID,
}
```

followed by:

```golang
for k, v := range metadata {
	subscriptionParams.AddMetadata(k, v)
}
```

this is what I can see in my Stripe dashboard:
![Screen Shot 2021-03-16 at 10 03 41 pm](https://user-images.githubusercontent.com/73058026/111298965-7bd0ba00-86a3-11eb-8a2e-1f4a57e9fb2b.png)

I'm using V 72.37.0.

**Comment by brandur-stripe** [comment] 2021-03-16 22:26
Hm, okay we don't have a full code sample here, but just to make sure: you are calling `AddMetadata` _before_ invoking `subschedule.New` right?

Here's a small patch that adds metadata in the test suite, and also prints the encoded form body:

``` patch
diff --git stripe.go stripe.go
index 93b7552..9dba9b8 100644
--- stripe.go
+++ stripe.go
@@ -284,6 +284,8 @@ func (s *BackendImplementation) CallRaw(method, path, key string, form *form.Val
 	if form != nil && !form.Empty() {
 		body = form.Encode()
 
+		fmt.Printf("body = %+v\n", string(body))
+
 		// On `GET`, move the payload into the URL
 		if method == http.MethodGet {
 			path += "?" + body
diff --git subschedule/client_test.go subschedule/client_test.go
index 75f1ac3..839a950 100644
--- subschedule/client_test.go
+++ subschedule/client_test.go
@@ -68,6 +68,7 @@ func TestSubscriptionScheduleNew(t *testing.T) {
 		},
 		EndBehavior: stripe.String(string(stripe.SubscriptionScheduleEndBehaviorCancel)),
 	}
+	params.AddMetadata("hello", "there")
 	schedule, err := New(params)
 	assert.Nil(t, err)
 	assert.NotNil(t, schedule)
```

As I run it, you can see the encoded metadata being added to the form right at the beginning:

> `body = metadata[hello]=there&customer=cus_123&end_behavior=cancel&phases[0][items][0][plan]=plan_123&phases[0][items][0][quantity]=10&phases[0][items][1][plan]=plan_456&phases[0][items][1][quantity]=20&phases[0][trial]=true&phases[1][items][0][plan]=plan_789&phases[1][items][0][quantity]=30&start_date=now`

**Comment by testfully-dev** [comment] 2021-03-17 08:38
> Hm, okay we don't have a full code sample here, but just to make sure: you are calling AddMetadata before invoking subschedule.New right?

Yep, I do `New` after I call `AddMetadata`.

> Here's a small patch that adds metadata in the test suite, and also prints the encoded form body:
Interesting. I will patch the module on my end and try to print the params to see what happens. 


Thanks for looking at this.

**Comment by testfully-dev** [comment] 2021-03-17 10:09
Okay, I tried to print body of "CallRaw" function and I can confirm that it contains the metadata. Below is an example:

```
this is body = metadata[from_billing_plan_monthly_price]=49&metadata[to_billing_plan_id]=prod_J6sZdxFpKqck1Q&metadata[requested_at]=Wed%2C+17+Mar+2021+21%3A01%3A06+AEDT&metadata[from_billing_plan_type]=monthly&metadata[scheduler_one_off_payment]=0.000000&metadata[scheduler_one_off_payment_date]=N%2FA&metadata[to_billing_plan_monthly_price]=99&metadata[from_billing_plan_started_at]=2021-03-17T20%3A55%3A49%2B11%3A00&metadata[from_billing_plan_name]=Lite&metadata[to_billing_plan_starts_at]=2021-04-16T21%3A01%3A05%2B10%3A00&metadata[switch_straight_away]=true&metadata[to_billing_plan_type]=monthly&metadata[to_billing_plan_name]=Plus&metadata[scheduler_one_off_payment_today]=49.500000&metadata[from_billing_plan_id]=prod_J6sYWcraVHM9IZ&customer=cus_J8CVINMuUE917t&end_behavior=release&phases[0][end_date]=1618570865&phases[0][items][0][price_data][currency]=usd&phases[0][items][0][price_data][product]=prod_Js6ZdxFpKcqk1Q&phases[0][items][0][price_data][recurring][interval]=month&phases[0][items][0][price_data][recurring][interval_count]=1&phases[0][items][0][price_data][unit_amount_decimal]=4950&phases[0][items][0][quantity]=1&phases[1][iterations]=190&phases[1][items][0][price]=price_1IUeoAI269faFK8kIeOfReep&phases[1][items][0][quantity]=1&phases[1][proration_behavior]=none&start_date=now
```

Yet the metadata doesn't show up in Stripe dashboard. I thought it might to do with the value of metadata so I tried a simple one using cURL:

```
curl https://api.stripe.com/v1/subscription_schedules \
  -u sk_test_ACCESS_TOKEN_FROM_STRIPE_HERE: \
  -d customer=cus_J8CVINMuUE971t \
  -d start_date=1615975266 \
  -d end_behavior=release \
  -d "phases[0][items][0][price]"=price_1IUenVI269faFKk8PdWbNCSi \
  -d "phases[0][items][0][quantity]"=1 \
  -d "phases[0][iterations]"=12 \
-d "metadata[foo]=bar"
```

and am getting the following response: 

```json
{
  "id": "sub_sched_1IVwCdI269faFK8kHm4CgGwQ",
  "object": "subscription_schedule",
  "canceled_at": null,
  "completed_at": null,
  "created": 1615975331,
  "current_phase": {
    "end_date": 1647511266,
    "start_date": 1615975266
  },
  "customer": "cus_J8CVINMuUE197t",
  "default_settings": {
    "application_fee_percent": null,
    "billing_cycle_anchor": "automatic",
    "billing_thresholds": null,
    "collection_method": "charge_automatically",
    "default_payment_method": null,
    "default_source": null,
    "invoice_settings": null,
    "transfer_data": null
  },
  "end_behavior": "release",
  "livemode": false,
  "metadata": {
    "foo": "bar"
  },
  "phases": [
    {
      "add_invoice_items": [

      ],
      "application_fee_percent": null,
      "billing_cycle_anchor": null,
      "billing_thresholds": null,
      "collection_method": null,
      "coupon": null,
      "default_payment_method": null,
      "default_tax_rates": [

      ],
      "end_date": 1647511266,
      "invoice_settings": null,
      "plans": [
        {
          "billing_thresholds": null,
          "plan": "price_1IUenVI269faFK8kPdWbNCSi",
          "price": "price_1IUenVI269faFK8kPdWbNCSi",
          "quantity": 1,
          "tax_rates": [

          ]
        }
      ],
      "prorate": true,
      "proration_behavior": "create_prorations",
      "start_date": 1615975266,
      "tax_percent": null,
      "transfer_data": null,
      "trial_end": null
    }
  ],
  "released_at": null,
  "released_subscription": null,
  "renewal_interval": null,
  "status": "active",
  "subscription": "sub_J8Cbm5nFMvEaot"
}
```

yet Stripe UI doesn't show the metadata for the subscription schedule

**Comment by testfully-dev** [comment] 2021-03-17 10:14
Update: 2 Tried to fetch one of my scheduled subscriptions using the following cURL command:

```
curl https://api.stripe.com/v1/subscription_schedules/sub_sched_1IVwLvI269faFK8ksHWBxKVK \
  -u sk_test_STRIPE_ACCESS_TOKEN
```

and API returns the schedule including the metadata:

```
{
  "id": "sub_sched_1IVwLvI269faFK8ksHWBxKVK",
  "object": "subscription_schedule",
  "canceled_at": null,
  "completed_at": null,
  "created": 1615975907,
  "current_phase": {
    "end_date": 2115799906,
    "start_date": 1615975906
  },
  "customer": "cus_J8ClJyQcfyHRVK",
  "default_settings": {
    "application_fee_percent": null,
    "billing_cycle_anchor": "automatic",
    "billing_thresholds": null,
    "collection_method": "charge_automatically",
    "default_payment_method": null,
    "default_source": null,
    "invoice_settings": null,
    "transfer_data": null
  },
  "end_behavior": "release",
  "livemode": false,
  "metadata": {
    "requested_at": "Wed, 17 Mar 2021 21:11:46 AEDT",
    "from_billing_plan_started_at": "0001-01-01T00:00:00Z",
    "to_billing_plan_name": "Lite",
    "from_billing_plan_type": "monthly",
    "to_billing_plan_type": "monthly",
    "switch_straight_away": "true",
    "to_billing_plan_monthly_price": "49",
    "from_billing_plan_monthly_price": "0",
    "to_billing_plan_id": "prod_J6sYWcraVHM9IZ",
    "scheduler_one_off_payment_date": "N/A",
    "from_billing_plan_name": "Free",
    "scheduler_one_off_payment": "0.000000",
    "from_billing_plan_id": "N/A",
    "to_billing_plan_starts_at": "2021-03-17T21:11:46+11:00",
    "scheduler_one_off_payment_today": "0.000000"
  },
  "phases": [
    {
      "add_invoice_items": [

      ],
      "application_fee_percent": null,
      "billing_cycle_anchor": null,
      "billing_thresholds": null,
      "collection_method": null,
      "coupon": null,
      "default_payment_method": null,
      "default_tax_rates": [

      ],
      "end_date": 2115799906,
      "invoice_settings": null,
      "plans": [
        {
          "billing_thresholds": null,
          "plan": "price_1IUenVI269faFK8kPdWbNCSi",
          "price": "price_1IUenVI269faFK8kPdWbNCSi",
          "quantity": 1,
          "tax_rates": [

          ]
        }
      ],
      "prorate": false,
      "proration_behavior": "none",
      "start_date": 1615975906,
      "tax_percent": null,
      "transfer_data": null,
      "trial_end": null
    }
  ],
  "released_at": null,
  "released_subscription": null,
  "renewal_interval": null,
  "status": "active",
  "subscription": "sub_J8Cl4LYtd40Uel"
}
```

sounds like a bug with Stripe UI. I shall report it to the team. I think we can close this issue. Thanks for helping with the debug.

**Comment by remi-stripe** [comment] 2021-03-17 15:02
@testfully-dev My guess here is that you expect to see the SubscriptionSchedule's metadata when the Dashboard shows you the Subscription's metadata instead. Those are separate objects in the API today and the Dashboard focuses on the latter once the Subscription is started, which is the case here.

You can't control the metadata of the Subscription through the SubscriptionSchedule today so you'll want to make sure you add the metadata to the Subscription after it's created!

Since it's not a bug with the library I agree we should close this out but don't hesitate to write in to our support team if you have more questions https://support.stripe.com/contact

**Closed by remi-stripe** 2021-03-17 15:02 UTC

**Comment by brandur-stripe** [comment] 2021-03-17 17:45
> Interesting. I will patch the module on my end and try to print the params to see what happens.

SG!

I also wanted to mention that one of my colleagues suggested that depending on exactly where you are in the Stripe dashboard, it may be that it's showing the metadata of a different object than you expect. For example, you've added metadata to the subscription schedule, but the dashboard is showing you the metadata for the associated _subscription_.

**Comment by brandur-stripe** [comment] 2021-03-17 17:46
And doh, I typed that seeing the first of @testfully-dev's comments showing up, but not the next two. A good reminder to reload pages before commenting. Thanks Remi!

**Comment by testfully-dev** [comment] 2021-03-19 08:40
> SG!
I also wanted to mention that one of my colleagues suggested that depending on exactly where you are in the Stripe dashboard, it may be that it's showing the metadata of a different object than you expect. For example, you've added metadata to the subscription schedule, but the dashboard is showing you the metadata for the associated subscription.

That was the case. The dashboard shows the underlying subscription that is managed by Stripe and it looks like that the metadata is not carried over to the subscription.

**Comment by brandur-stripe** [comment] 2021-03-19 22:17
> That was the case. The dashboard shows the underlying subscription that is managed by Stripe and it looks like that the metadata is not carried over to the subscription.

Good to know! Glad it's resolved.

And yeah, just for future reference, metadata tends to all be completely independent across objects. This is by design so that you have perfect control over setting it with as much granularity as you want.
