### ISSUE TITLE
Update subscription with multiple plans

### ISSUE THREAD

**Issue by layby42** [stripe/stripe-go#423] opened 2017-06-19 19:35 UTC
Hi Everybody,

We are trying to update one-plan-subscription (plan id = "test2") with second plan and getting error:  _Cannot add multiple subscription items with the same plan PlanId_.

stripe-go _params_ in  Update function (/sub/client.go) seem to be OK:

> {...,"Plan":"",...,"Items":[{"...,"Quantity":0,"Plan":"test2","Deleted":false,...},{"...,"Quantity":0,"Plan":"addon1","Deleted":false,...}],...}

Error returned by
> c.B.Call("POST", fmt.Sprintf("/subscriptions/%v", id), token, body, commonParams, sub)

We can use https://stripe.com/docs/api#subscription_items multi-step create/update/delete endpoints theoretically, but prefer single subscription update because we need to change set of plans (1 or more) to another set of plans (1 or more) for existing subscription as one operation and it looks like it supposed to be possible according to https://stripe.com/docs/api#update_subscription or not?

version: 22.1.0

Thanks.

**Comment by brandur-stripe** [comment] 2017-06-20 00:31
Hi there,

Sorry about the trouble. I'm not 100% sure, but this may be a bug in our backend ... I've asked the appropriate team to look into it, and will get back to you.

**Comment by remi-stripe** [comment] 2017-06-20 06:02
@layby42 This issue was fixed in 22.1.1 where the `deleted` parameter was properly taken into account on subscription items update. Can you try the latest version first and confirm that this issue is not happening anymore?

**Comment by layby42** [comment] 2017-06-20 14:22
@remi-stripe, I've upgraded to 22.6.0. Same error returned by _c.B.Call("POST", fmt.Sprintf("/subscriptions/%v", id), token, body, commonParams, sub)_

> &stripe.Error{Type:"invalid_request_error", Msg:"Cannot add multiple subscription items with the same plan: test2", Code:"", Param:"plan", RequestID:"req_AsXXUl40AxUjxk", HTTPStatusCode:400, ChargeID:"", Err:(*stripe.InvalidRequestError)(0xc420756198)}

 What I've noticed

- create new subscription with **multiple plans** with/without coupon works
- update this very subscription with same data with/without coupon returns error ("Cannot add multiple subscription items with the same plan: test2")
- any attempts update this very subscription fail same way ("Cannot add multiple subscription items with the same plan: test2"), including attempt to remove coupon or update subscription to one plan

But

- create new subsription with **one plan** without coupon works
- update this very subscription with same data without coupon works
- update this very subscription with coupon works
- update this very subscription with same data with coupon works
- update this very subscription by removing coupon works
- update this very subscription with multiple plan fails ("Cannot add multiple subscription items with the same plan: test2")

i.e. looks like something is wrong with **update** subscription:
- update single-plan subscription with multiple plan fails
- update multiple-plans subscription with multiple plans (even the same set of multiple plans) fails
- attempt to remove coupon from multiple plan subscription fails
- update multiple-plans subscription with single-plan fails

**Comment by remi-stripe** [comment] 2017-06-20 14:39
@layby42 I just tried to update a subscription to add a new plan and remove the existing one or to keep the existing one and add an extra one and it worked both times.

Can you provide me with the exact code you're currently using to trigger an error and an example request id `req_XXXXX` where it failed?

**Comment by remi-stripe** [comment] 2017-06-20 14:44
@layby42 Okay I think I got the issue here. You should not be passing the existing plan id when you update the subscription. Instead, you should only pass the *new* plan ids. You can explicitly pass the existing subscription ids and pass `Deleted: false` if you want. Here's an example go code that creates and then updates the subscription:

```
  customerParams := &stripe.CustomerParams{
    Desc: "Customer created via Go",
  }
  customerParams.SetSource("tok_visa")

  c, err := customer.New(customerParams)

  s, err := sub.New(&stripe.SubParams{
    Customer: c.ID,
    Items: []*stripe.SubItemsParams{
      {
        Plan: "plan20usdmonthly",
        Quantity: 1,
      },
      {
        Plan: "plan30usdmonthly",
        Quantity: 1,
      },
    },
  })

  fmt.Printf("\nSubscription: \n", s, err)

  s2, err := sub.Update(
    s.ID,
    &stripe.SubParams{
      Items: []*stripe.SubItemsParams{
        {
          ID: s.Items.Values[0].ID,
          Deleted: false,
        },
        {
          ID: s.Items.Values[1].ID,
          Quantity: 1,
        },
        {
          Plan: "plan10usdmonthly",
          Quantity: 1,
        },
      },
    },
  )

  fmt.Printf("\nUpdated subscription: \n", s2, err)
```

This code creates a subscription to 2 plans and then updates it to change the quantity of the second item from 1 to 2 and also add an extra plan.

**Comment by layby42** [comment] 2017-06-20 14:52
@remi-stripe, thank you for the quick reply. Could you please check the very first comment, you will see "Deleted": false in params for both plans. Shouldn't it be enough? 

The issue with "do not include unchanged plans": we just do not know 100% what set of plans stripe currently have for subscription becuase it is possible that subscription got modified directly via stripe dashboard and our "last state" could be outdated. So we would like to have a way to post whole set of plans the way they supposed to be, i.e. delete what was not posted and add/update what was posted.

**Comment by remi-stripe** [comment] 2017-06-20 15:11
@layby42 the issue is that you should not be passing the plan id in that case. You should be passing the **subscription item id** the one with `si_XXXXX`. You would have to retrieve the subscription upfront in that case before updating though I would recommend providing a UI showing all plans/items active and only updating what changed.

**Comment by layby42** [comment] 2017-06-20 15:20
@remi-stripe, thanks, "passing the subscription item id the one with si_XXXXX" is the same with loading current state from stripe + compare it with new state + call one by one updates for subscription items or one update with difference for subscription... 

Also I got this error when trying to update multi-plan subscription with one plan subscription:

>  &stripe.Error{Type:"invalid_request_error", Msg:"Cannot update using plan parameter when multiple plans exist on the subscription. Updates must be made to individual items instead.", Code:"", Param:"", RequestID:"req_AsZ9sBBwz9KqZP", HTTPStatusCode:400, ChargeID:"", Err:(*stripe.InvalidRequestError)(0xc42000e778)}

in other words there is no easy way to update subscription with set of plans

**Comment by remi-stripe** [comment] 2017-06-20 15:22
@layby42 I think there's some confusion around the logic here. When you call "update" you are not wiping the slate clean and taking only the new parameters into account. That's not how our Update Subscription API works. It's additive to what already exists.

Unfortunately, the way you approach it will not work, not unless you explicitly delete *all* the subscription items *and* add the new plans in the list, though that part does not seem efficient.

You do need to keep track of what's in the subscription and each plan corresponding to each subscription item and then keep the ones you want to keep, delete the ones you don't need anymore and finally add all the new plans.

**Comment by layby42** [comment] 2017-06-20 15:26
@remi-stripe 
> You do need to keep track of what's in the subscription and each plan corresponding to each subscription item and then keep the ones you want to keep, delete the ones you don't need anymore and finally add all the new plans.

we do keep the track, but I was hoping to have it just as reference. thank, we'll re-implement the way we are working with subscriptions

**Comment by remi-stripe** [comment] 2017-06-20 15:28
Sure! Let me know if you're still hitting issues after that though as the Go library works a bit differently from most of our other libraries!

**Closed by remi-stripe** 2017-06-20 15:28 UTC

**Comment by layby42** [comment] 2017-06-20 16:34
hi @remi-stripe, sorry, quick question

- let's say you have subscription with one plan, i.e. no subscription items
- you need to change this plan (main plan in our case) to another one and add one more (add-on)
- is there a way to do it as one operation: subscription update?  original plan does not have subscription item id because there are no items, so I cannot remove it as "subscription_item_id + deleted:true" or change it as "subscription_item_id + plan:new_plan_id"

**Comment by remi-stripe** [comment] 2017-06-20 17:46
@layby42 If you have a subscription with just one plan and no subscription item, you would simply update the plan. The code would look like this:

```
s, err := sub.Update(
    "sub_XXXX",
    &stripe.SubParams{
        Plan: "new_plan_id",
    },
)
```

**Comment by layby42** [comment] 2017-06-20 17:49
@remi-stripe, in other words there is not way to do both "update plan" and "add another" in one step, I have to do it in two steps:

- first update plan for one-plan subscription
- next add another plan to already updated subscription

i.e. two operations, two invoices

**Comment by remi-stripe** [comment] 2017-06-20 17:54
@layby42 Oh sorry I misunderstood the question then. I thought you explicitly wanted to handle subscriptions with just one plan the old way.

Any subscription created, even with one plan, will have a subscription item with a unique `si_XXXX` identifier that you can then use to update the subscription afterwards. That update would delete the current one, and simply add two new plans instead.

**Comment by layby42** [comment] 2017-06-20 18:12
@remi-stripe thank you, it was my mistake, I've ignored items for one plan subscription

**Comment by ManishaSrivastava** [comment] 2018-03-23 21:57
@remi-stripe : can you please provide the code in java , i am experincing the same issue not able to update the subscription with multiple plan
@layby42 Okay I think I got the issue here. You should not be passing the existing plan id when you update the subscription. Instead, you should only pass the new plan ids. You can explicitly pass the existing subscription item ids and pass Deleted: false if you want. Here's an example go code that creates and then updates the subscription:

  customerParams := &stripe.CustomerParams{
    Desc: "Customer created via Go",
  }
  customerParams.SetSource("tok_visa")

  c, err := customer.New(customerParams)

  s, err := sub.New(&stripe.SubParams{
    Customer: c.ID,
    Items: []*stripe.SubItemsParams{
      {
        Plan: "plan20usdmonthly",
        Quantity: 1,
      },
      {
        Plan: "plan30usdmonthly",
        Quantity: 1,
      },
    },
  })

  fmt.Printf("\nSubscription: \n", s, err)

  s2, err := sub.Update(
    s.ID,
    &stripe.SubParams{
      Items: []*stripe.SubItemsParams{
        {
          ID: s.Items.Values[0].ID,
          Deleted: false,
        },
        {
          ID: s.Items.Values[1].ID,
          Quantity: 1,
        },
        {
          Plan: "plan10usdmonthly",
          Quantity: 1,
        },
      },
    },
  )

  fmt.Printf("\nUpdated subscription: \n", s2, err)

**Comment by remi-stripe** [comment] 2018-03-23 22:03
@ManishaSrivastava You should reach out to our support team and they can help you debug this quickly! Since this issue is about an old issue with stripe-go, it's not really the best place to debug this.
