### ISSUE TITLE
Transfer destination

### ISSUE THREAD

**Issue by layby42** [stripe/stripe-go#283] opened 2016-07-27 20:18 UTC
Hi Everybody,

Is it possible to extend Transfer struct with destination?

type Transfer struct {
        ...
	Dest           *Account           `json:"destination"`
        ...
}

Also (not sure if I should ask it there or stripe support): when transfers were done to recipients there always was non-empty Bank (*BankAccount) in transfer details. Now, when I'm trying to make transfer to account: Bank is empty. Is it how it supposed to be with transfers to accounts / managed accounts?

**Comment by MDrollette** [comment] 2016-08-03 21:37
This is also asked in #193. The problem is the `destination` can be multiple types, not just an Account.

**Comment by layby42** [comment] 2016-08-03 21:45
So there will be no way to find out destination? Can it be interface{} instead of *Account?

**Comment by MDrollette** [comment] 2016-08-18 16:07
@layby42 The latest release [adds support](https://github.com/stripe/stripe-go/commit/e894799911e0a6e1fbaf735c4900a2d1f735c1cf) for this. You can now inspect the `Type` property on the `Dest` of a `Transfer` to know which property is expanded and get access to it.

```go
tr, _ := stripe.Transfers.Get("tr_xxxxx", &stripe.TransferParams{Params: stripe.Params{Exp: []string{"destination"}}})
switch tr.Dest.Type {
case stripe.TransferDestinationAccount:
        // tr.Dest.Account will be set to the &stripe.Account that received this transfer
case stripe.TransferDestinationBankAccount:
        // tr.Dest.BankAccount will be set to the &stripe.BankAccount that received this transfer
}
```

The possible types are shown here https://github.com/stripe/stripe-go/blob/master/transfer.go#L27-L37

**Comment by brandur** [comment] 2016-08-18 18:43
Yes! Thank-you once again for this @MDrollette!

@layby42 I'm going to close this down for now, but let us know if you run into anymore trouble.

**Closed by brandur** 2016-08-18 18:43 UTC
