### ISSUE TITLE
Multiple retries when status is 200

### ISSUE THREAD

**Issue by cbr4yan** [stripe/stripe-go#1523] opened 2022-08-10 15:43 UTC
### Describe the bug

Hi,

We are creating paymentIntents and have detected a retry behavior that is causing errors:

First case: a creation request is made with status 429-lock-timeout, which stripe-go retries, in the dashboard logs we see that 3 requests have been made for the retry, with the result 200, 409, 409 (in that order). So, the result 200 did not stop the retry. We know it is done by the retry because the idempotency key is generated only in the request, the do retry is based on the same request.

second case: We have seen in the request logs that a request was made with status 200 and then the same request was retried again, with the same result 200.

In our code we only make the call once, it can be tested since the requests have the same idempotency key (ulid).

Thanks

### To Reproduce

The behavior does not follow a specific pattern, so we do not know how to reproduce it.

### Expected behavior

When the response of the request is 200, it should not be reattempted, since it is sequential.

### OS

Linux

### Go version

Go 1.17

### stripe-go version

V72.120.0

### API version

2020-08-07

**Comment by remi-stripe** [comment] 2022-08-10 16:22
@cbr4yan Thanks for the report. This is not a bug with the stripe-go library in that case as it is not initiating the retry that caused the 200. I'm going to close this out as Github issues should be limited to bugs with the library itself.

I've seen discussions of this behaviour internally and I think you might already be working with our support team to analyze this and they provided more details already. If you aren't talking with our support team already though, I'd recommend that you reach out to them, mention this github issue and provide example request ids so that they can look into this with you directly.

**Closed by remi-stripe** 2022-08-10 16:22 UTC
Labels: bug
