### ISSUE TITLE
Feature Request: Checkout Session Line Items Metadata

### ISSUE THREAD

**Issue by SUSTAPLE117** [stripe/stripe-go#1232] opened 2020-11-30 01:21 UTC
Go version: 1.15.5
Stripe-go version: v72.27.0
As shown in the documentation here: https://stripe.com/docs/api/checkout/sessions/line_items#retrieve_checkout_session_line_items

When line_items are retrieved for a session the metadata is returned but not available in the stripe.LineItem struct: https://pkg.go.dev/github.com/stripe/stripe-go/v72#LineItem

I want to use metadata to add information about my line items that I can consume when fulfilling a successful checkout session.

**Comment by paulasjes-stripe** [comment] 2020-11-30 03:53
`metadata` is available on the [Checkout Session level](https://stripe.com/docs/api/checkout/sessions/object#checkout_session_object-metadata), but not on the [`line_item` level](https://stripe.com/docs/api/checkout/sessions/object#checkout_session_object-line_items) of a Checkout Session. 

As such this as working as intended as the metadata can be retrieved from the Checkout Session type: https://pkg.go.dev/github.com/stripe/stripe-go/v72#CheckoutSession. 

You might instead be referring to the metadata in the API ref example of retrieving line items, which is a representation of the metadata set on on the [Price object](https://pkg.go.dev/github.com/stripe/stripe-go/v72#Price).

Since this isn't a bug or issue with the stripe-go library itself, I'm going to close it. If you want metadata support on line items, I suggest reaching out to Stripe support with API feature requests: https://support.stripe.com/contact

**Closed by paulasjes-stripe** 2020-11-30 03:53 UTC

**Comment by SUSTAPLE117** [comment] 2020-12-03 16:52
@paulasjes-stripe sorry for the late reply. So I define my line items like this: 
```

&stripe.CheckoutSessionLineItemParams{
	Name: stripe.String(productToBuy.Name),
	PriceData: &stripe.CheckoutSessionLineItemPriceDataParams{
		Currency:   stripe.String("CAD"),
		UnitAmount: stripe.Int64(1),
		ProductData: &stripe.CheckoutSessionLineItemPriceDataProductDataParams{
			Name: stripe.String("productName"),
			Metadata: map[string]string{
						//metadata here
			},
		},
	},
	Quantity: stripe.Int64(1),
}

```

So if I understand correctly I can go fetch the Price Object associated to extract the metadata fields?

Thanks

**Comment by remi-stripe** [comment] 2020-12-04 03:23
@SUSTAPLE117 Your code is setting metadata on the `Product` object, not the `Price`. When you retrieve a Checkout `Session`, you would need to expand `line_items.data.price.product` to get the full `Product` object and access the product's metadata directly. You can read more about expand here: https://stripe.com/docs/expand

I'd recommend talking to our support team directly if you have any follow up questions!

**Comment by SUSTAPLE117** [comment] 2020-12-04 03:28
@remi-stripe thanks!
