### ISSUE TITLE
API.BankAccounts.New() doesn't add Metadata to created bank account.

### ISSUE THREAD

**Issue by lsmith130** [stripe/stripe-go#685] opened 2018-09-03 14:46 UTC
Using go 1.11 and stripe-go v45.0.0.

```
bankAcct, err := s.stripe.BankAccounts.New(&stripe.BankAccountParams{
	Token:    &token.StripeBankAccountToken,
	Customer: &account.StripeCustomerID,
	Params: stripe.Params{
		Context: ctx,
		Metadata: map[string]string{
			"ABC": "123",
		},
	},
})
if err != nil {
	log.Printf("CreatePaymentMethod: create bank account: %v", err)
	return nil, err
}
log.Println(bankAcct.Metadata)
```
prints
```
2018/09/03 14:42:58 paymentmethod.go:215: map[]
```
My workaround is to update the bank account with metadata once it's been created, but it took me a while to figure out what was going on, and it would be nice to save others from the same trouble in the future.

**Comment by remi-stripe** [comment] 2018-09-04 14:35
@lsmith130 Thanks a lot for the detailed report. I looked into this for a while and I think this issue is that `bankaccount.New` uses `CallRaw` instead of `Call` because it does the params encoding differently.
The issue is that the handling of `params.Params` is done in `Call` instead. So if you use `CallRaw` you don't handle `params.Params` properly which is where the metadata are stored.

Assigning to @brandur-stripe to investigate the right fix as this one is a bit beyond me.

**Closed** 2018-09-04 20:05 UTC
