### ISSUE TITLE
setupintent.go - missing fields in NextActionUseStripeSDK

### ISSUE THREAD

**Issue by Reclaf** [stripe/stripe-go#1445] opened 2022-04-06 14:02 UTC
Using setupintent.Confirm function I have tried to recieve StripeJS URL, but there was always empty response for next_action part.

Using the same functions and data in Python I found out, that Python have no problems with showing these values.
Stripe GUI also shows next_action in response body.

After investigation I found out, that there are no fields in NextAction (SetupIntentNextActionUseStripeSDK) struct.

**Comment by remi-stripe** [comment] 2022-04-06 18:26
@Reclaf The goal of `use_stripe_sdk` as a "next action" is to be something opaque you never look into. The format is specifically for our client-side libraries such as Stripe.js or Mobile SDKs to handle the next steps. You are not supposed to look inside the hash and pull information out of it. If you do, your integration would break in the future when we make changes to that shape or the format of the URL, which we've done a few times over the years.

Your integration is supposed to use one of our official client-side libraries to confirm that SetupIntent directly.

I'm going to close this out as it's not a bug with the library itself and more an integration question. I'd recommend working with our support team directly instead: https://support.stripe.com/contact

**Closed by remi-stripe** 2022-04-06 18:26 UTC
