### ISSUE TITLE
TransactionSource object not expandable

### ISSUE THREAD

**Issue by cristianpontes** [stripe/stripe-go#539] opened 2018-04-05 08:40 UTC
The `TransactionSource` has several objects inside that should be populated when using the `expand` parameter. The only thing that prevents this to happen is the fact that those fields do not have the right JSON key related. 

Take the following example as a use case:

```go
        transactionReqParams := &stripe.TxListParams{}
	transactionReqParams.Expand("data.source.source_transfer")
	transactions := c.strp.Balance.List(transactionReqParams)

	for transactions.Next() {
		transactionType = string(payoutTransactions.Transaction().Type)
		if transactionType != "payment" {
			continue
		}
                // causes an error
		chargeID := transactions.Transaction().Src.Transfer.SourceTx.ID
	}
```

This gets solved if we modify the `TransactionSource` struct like this:

```go
type TransactionSource struct {
	Type              TransactionSourceType `json:"object"`
	ID                string                `json:"id"`
	Charge            *Charge               `json:"-"`
	Dispute           *Dispute              `json:"-"`
	Fee               *Fee                  `json:"-"`
	Payout            *Payout               `json:"-"`
	RecipientTransfer *RecipientTransfer    `json:"-"`
	Refund            *Refund               `json:"-"`
	Reversal          *Reversal             `json:"-"`
	Transfer          *Transfer             `json:"source_transfer"` // changed here, set the right json key
}
```

Is there any reason for all those fields having no proper json key?

**Comment by brandur-stripe** [comment] 2018-04-06 19:06
Hey @cristianpontes, sorry to hear about the trouble here!

Did you confirm that adding the new JSON annotation fixes the problem for you? `TransactionSource` is kind of a weird one because what's supposed to happen is that a custom unmarshaler takes over and populates the `Transfer` field within that structs (that's why all of the fields are currently marked `json:"-"`):

``` go
func (s *TransactionSource) UnmarshalJSON(data []byte) error {
	type source TransactionSource
	var ss source
	err := json.Unmarshal(data, &ss)
	if err == nil {
		*s = TransactionSource(ss)

		switch s.Type {
		case TransactionSourceCharge:
			err = json.Unmarshal(data, &s.Charge)
		case TransactionSourceDispute:
			err = json.Unmarshal(data, &s.Dispute)
		case TransactionSourceFee:
			err = json.Unmarshal(data, &s.Fee)
		case TransactionSourcePayout:
			err = json.Unmarshal(data, &s.Payout)
		case TransactionSourceRecipientTransfer:
			err = json.Unmarshal(data, &s.RecipientTransfer)
		case TransactionSourceRefund:
			err = json.Unmarshal(data, &s.Refund)
		case TransactionSourceReversal:
			err = json.Unmarshal(data, &s.Reversal)
		case TransactionSourceTransfer:
			err = json.Unmarshal(data, &s.Transfer)
		}

		if err != nil {
			return err
		}
	} else {
		// the id is surrounded by "\" characters, so strip them
		s.ID = string(data[1 : len(data)-1])
	}

	return nil
}
```

**Comment by cristianpontes** [comment] 2018-04-06 19:48
Hey @brandur-stripe 

Thanks for the clarifications. I didn't see that unmarshal custom.

However, I can confirm that adding the JSON tag solves the problem. 

I could be wrong, but the value for constant `TransactionSourceTransfer` is `transfer` whereas the API returns that field as `source_transfer`, which is the value that I manually set on the struct. 

Maybe the problem is the misnaming of that field, or maybe there are cases where that field can be returned as `transfer` and other times where the field will be returned as `source_transfer`

Thanks.

**Comment by brandur-stripe** [comment] 2018-04-09 22:03
> I could be wrong, but the value for constant TransactionSourceTransfer is transfer whereas the API returns that field as source_transfer, which is the value that I manually set on the struct.

I think what it's supposed to be checking here is the value of the `type` field, rather than the presence of any particular fields on the response.

I'm having a little bit of a hard time seeing what's going on here because all these transactions can have such dramatically different structures nested in them. Would you mind sending me the ID of a sample transaction that's causing this sort of trouble? (i.e., like `txn_*`) I think being able to see the full structure will make finding the right way to resolve this much easier. Thanks!

**Comment by brandur-stripe** [comment] 2018-07-19 00:45
@cristianpontes We've made a lot of improvements in the last few months to how unmarshaling works (maybe most importantly here, we no longer swallow errors, so you should be able to see exactly what the problem is here).

Could you try upgrading stripe-go and letting us know whether this is still a problem? I'm going to close this issue for now, but we can reopen if it's still persistent.

**Closed by brandur-stripe** 2018-07-19 00:45 UTC
