### ISSUE TITLE
Error during charge create.

### ISSUE THREAD

**Issue by Swatiparbhakar** [stripe/stripe-go#490] opened 2017-10-30 06:54 UTC
Hello,
I am facing an issue during charge create. "Stripe Payment: Getting Error as Customer cus_***** does not have a linked card with ID tok_*****".
I have customer Id and token during create charge.
My code is give below:
<pre>
    chargeParams := &stripe.ChargeParams{
      Amount: 2000,
      Currency: "usd",
      Customer: "cus_123",
    }
    chargeParams.SetSource("token_dsd")
    ch, err := charge.New(chargeParams)
</pre>

**Comment by ob-stripe** [comment] 2017-10-30 08:56
Hi @Swatiparbhakar. You cannot create a charge by passing both a customer and a token ID. You must either:

- pass only a token ID in the `source` parameter, and omit the `customer` parameter. In this case, the card represented by the token will be used for the charge and the token will be consumed.

- pass only a customer ID in the `customer` parameter and omit the `source` parameter. In this case, the customer's default source will be used for the charge.

- pass a customer ID in the `customer` parameter and a card ID (`"card_..."`) in the `source` parameter. The card must belong to the customer. In this case, the specific card will be used for the charge.

As this is not a bug with the Go library, I'm closing the issue. If you require further help, please send a message to support using the form at https://support.stripe.com/email.

**Closed by ob-stripe** 2017-10-30 08:56 UTC
